name    'netmanagers-fail2ban'
version '1.1.1'
author  'Javier Bertoli'
license 'Apache2'
project_page 'http://www.netmanagers.com.ar'
source  'https://github.com/netmanagers/puppet-fail2ban'
summary 'Puppet module for fail2ban'
description 'This module installs and manages fail2ban. Check README for details.'
dependency 'ripienaar/concat', '>=0.2.0'
dependency 'example42/puppi', '>= 2.0.0'
dependency 'example42/monitor', '>= 2.0.0'
